### PR TITLE
Fixed policy CMP0053 warning in CMake 3

### PR DESCRIPTION
**Pull request by hernando**

### CODE REVIEW

**Comment by hernando** [comment]
@tribal-tec can you review and merge?

**Comment by tribal-tec** [comment]
this works still with cmake 2.8?

**Comment by hernando** [comment]
Why not? ${} substitution happens at parse time not during configure_file, so @ONLY has no effect on it. But I'll double check just in case.

**Comment by hernando** [comment]
works as expected

**Pull request merged**
